npm install -g bower
bower install --save BlackrockDigital/startbootstrap-sb-admin-2
bower install --save almasaeed2010/AdminLTE
bower install --save jquery
bower install --save jquery-ui
bower install --save moment
bower install --save bootstrap
bower install --save font-awesome
bower install --save jquery-migrate
bower install --save chart.js
bower install --save three.js
bower install --save tinymce
bower install --save gridstack
bower install --save jqueryui-touch-punch
bower install --save jquery.easing
bower install --save magnific-popup
bower install --save sweetalert
bower install --save typeahead.js
bower install --save bootstrap-daterangepicker
bower install --save flag-icon-css
bower install --save MDBootstrap
bower install --save jquery-timepicker-wvega
bower install --save list.js
bower install --save datatables
bower install --save bootstrap-select
bower install --save bootstrap-language
bower install --save bootstrap-languages
bower install --save dbushell/Nestable
bower install --save ilikenwf/nestedSortable
bower install --save jquery.ui.touch-punch
bower install --save ContentTools
bower install --save jquery.imgareaselect
bower install --save blueimp/jQuery-File-Upload
bower install --save blueimp/JavaScript-Load-Image
bower install --save blueimp/JavaScript-Canvas-to-Blob
bower install --save multiselect
bower install --save bower
bower install --save bootstrap-tagsinput/bootstrap-tagsinput
bower install --save infinite-scroll
bower install --save geocomplete
bower install --save googlemaps/v3-utility-library
bower install --save wpic/bootstrap-switch
bower install --save bootstrap-social
bower install --save wpic/bootstrap-number-input
bower install --save cookieconsent
bower install --save ContentEdit
bower install --save GetmeUK/ContentFlow
bower install --save Font-Awesome
bower install --save content-tools
bower install --save Magnific-Popup
bower install --save UniSharp/laravel-filemanager
bower install --save matchheight
bower install --save blivesta/animsition
bower install --save fronteed/icheck
bower install --save Leaflet/Leaflet.markercluster
bower install --save Leaflet/Leaflet.fullscreen