composer require guzzlehttp/guzzle
composer require UniSharp/laravel-filemanager
composer require algolia/algoliasearch-client-php 
composer require barryvdh/laravel-ide-helper 
composer require beelab/bowerphp 
composer require doctrine/dbal 
composer require facebook/graph-sdk 
composer require fideloper/proxy 
composer require intervention/httpauth
composer require intervention/image 
composer require intervention/imagecache 
composer require kriswallsmith/assetic 
composer require laravel/scout 
composer require laravel/socialite 
composer require laravelcollective/html 
composer require leafo/lessphp 
composer require leafo/scssphp 
composer require lmammino/jsmin4assetic 
composer require mcamara/laravel-localization 
composer require mrclay/jsmin-php 
composer require mrclay/minify 
composer require natxet/CssMin 
composer require patchwork/jsqueeze 
composer require psy/psysh
composer require ptachoire/cssembed 
composer require spatie/laravel-cookie-consent 
composer require spatie/laravel-feed 
composer require spatie/laravel-image-optimizer 
composer require spatie/laravel-partialcache 
composer require spatie/laravel-sitemap 
composer require symfony/css-selector 
composer require symfony/dom-crawler 
composer require symfony/polyfill-php70
composer require teamtnt/laravel-scout-tntsearch-driver 
composer require twig/twig 
composer require zendframework/zend-config